---

- name: Install dependancies from apt
  become: yes
  apt:
    name: ['nodejs', 'arp-scan', 'mariadb-server', 'redis-server']
    state: present

- name: Install NPM
  shell: curl -L https://www.npmjs.com/install.sh | sh
  become: yes

- name: Install npm packages globally
  npm:
    name: nodemon
    global: yes
  become: yes

- name: Creates an entry like "@reboot /some/job.sh"
  cron:
    user: pi
    name: "Master"
    special_time: reboot
    job: "/usr/local/bin/nodemon -w /home/pi/homebox-ui/api -w /home/pi/homebox-ui/config /home/pi/homebox-ui/app.js > /var/log/homebox-ui.log 2>&1"
  become: yes


- name: Sensors refresh
  cron:
    user: pi
    name: "Sensors Refresh"
    job: "/usr/bin/wget -q -O /dev/null http://localhost:8080/api/v1/sensors/refresh  >/dev/null 2>&1"

- name: Devices redresh
  cron:
    user: pi
    name: "Devices Refresh"
    job: "/usr/bin/wget -q -O /dev/null http://localhost:8080/api/v1/devices/refresh  >/dev/null 2>&1"
  become: yes

- file:
    path: /var/log/homebox-ui.log
    owner: pi
    group: pi
    # when specifying mode using octal numbers, add a leading 0
    mode: 0644