---

- name: Start ui
  shell: pm2 stop ui ; pm2 delete ui ; pm2 start /home/pi/homebox-ui/process.json
  ignore_errors: yes

- name: Save ui
  shell: pm2 save


- name: Sensors refresh
  cron:
    user: pi
    name: "Sensors refresh"
    job: "/usr/bin/wget -q -O /dev/null http://localhost:8080/api/v1/sensors/refresh  >/dev/null 2>&1"

- name: Devices redresh
  cron:
    user: pi
    name: "Devices refresh"
    job: "/usr/bin/wget -q -O /dev/null http://localhost:8080/api/v1/devices/refresh  >/dev/null 2>&1"
  become: yes

- name: Webcams redresh
  cron:
    user: pi
    name: "Webcams refresh"
    job: "/usr/bin/wget -q -O /dev/null http://localhost:8080/api/v1/webcams/refresh  >/dev/null 2>&1"
  become: yes