---

- name: Start probe
  shell: pm2 stop ui ; pm2 delete ui ; pm2 start /home/pi/homebox-probe/process.json ; pm2 save
  ignore_errors: yes

- name: Save probe
  shell: pm2 save

- name: Creates an entry like "@reboot /some/job.sh"
  cron:
    user: pi
    name: "Probe webcam"
    job: "fswebcam -S 30 -F 5 -d /dev/video0 -r 1920x1080 /home/pi/homebox-probe/assets/images/webcam.jpg"
  become: yes