---

- name: Install dependancies from apt
  become: yes
  apt: 
    name: ['nodejs']
    state: present

- name: Get NPM version
  shell: npm -v | egrep '^[0-9]*\.[0-9]*' -o
  register: npm_shell_output

- debug: msg="{{ npm_shell_output.stdout}}"

- name: Install NPM
  shell: curl -L https://www.npmjs.com/install.sh | sh
  when: npm_shell_output.stdout is version('6.5','<')
  become: yes
  ignore_errors: yes

- name: Install npm packages globally
  npm:
    name: pm2
    global: yes
  become: yes

- name: Install PM2 systemd
  shell: env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u pi --hp /home/pi
  become: yes