---
- name: Install dependancies from apt
  become: yes
  apt:
    name: ['build-essential', 'python-pip', 'python-dev', 'python-smbus', 'python-openssl', 'git', 'python3-pip', 'libffi-dev', 'libssl-dev']
    state: present

- name: check if file exists
  stat: 
    path: /home/pi/homebox-build/wiringPi
  register: file_exists

- git:
    repo: 'git://git.drogon.net/wiringPi'
    dest: /home/pi/homebox-build/wiringPi
  when: file_exists.stat.exists == False

- name: Run Py script
  command: ./build
  args:
    chdir: /home/pi/homebox-build/wiringPi/
  when: file_exists.stat.exists == False

